# Generated by Django 2.1.4 on 2020-07-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ('pub_date',)},
        ),
    ]
