# Generated by Django 2.1.4 on 2020-07-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20200704_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ('-pub_date',)},
        ),
    ]
