# Generated by Django 2.0.5 on 2020-07-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20200705_1515'),
        ('adverts', '0004_like'),
    ]

    operations = [
    ]
