# Generated by Django 2.1.4 on 2020-07-05 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0005_auto_20200705_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='likes',
            field=models.ManyToManyField(related_name='advertposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
