# Generated by Django 2.0.5 on 2020-07-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_auto_20200705_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
