# Generated by Django 2.0.5 on 2020-07-06 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_auto_20200705_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='adverts.Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='adverts.Location'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='adverts.Option'),
        ),
    ]
