# Generated by Django 2.0.5 on 2020-07-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_review'),
        ('adverts', '0006_advert_likes'),
    ]

    operations = [
    ]
