# Generated by Django 2.0.5 on 2020-07-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0012_auto_20200707_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
